- setup:

- name: Stop service
  systemd:
    scope: user
    name: "{{ ya_provider_unit_name }}{{ item }}"
    enabled: no
    state: stopped
  loop:
    - .service
    - -promtail.service
    - -clean.timer
    - -clean.service
  ignore_errors: yes  # go on if unit doesn't exist

- name: Delete subnet dir
  file:
    path: "{{ ya_provider_subnet_dir }}"
    state: absent

- name: Delete systemd unit
  file:
    dest: "{{ ansible_user_dir }}/.config/systemd/user/{{ ya_provider_unit_name }}{{ item }}"
    state: absent
  loop:
    - .service
    - -promtail.service
    - -clean.timer
    - -clean.service

- name: Reload systemd
  systemd:
    scope: user
    daemon_reload: yes
